name: Build Image

on:
  workflow_dispatch:
    inputs:
      tags:
        description: The tags that will be applied to the image.
        required: true
        default: '["latest"]'
      # List the required build arguments here.
      builder-tag:
        description: The builder image tag to build a runtime image for.
        required: true

jobs:
  build-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Infer builder image alpine version
        id: infer-alpine-version
        env:
          BUILDER_TAG: ${{ inputs.builder-tag }}
        run: |
          if test "${{ runner.debug }}" = "1"; then
            set -x
          fi
          
          echo "inferring alpine version for builder image with tag ${{ inputs.builder-tag }}"
          alpine_version=$(BUILDER_TAG=${BUILDER_TAG} ./scripts/builder-alpine-version.sh)
          echo "inferred: \"${alpine_version}\""
          
          echo "alpine-version=${alpine_version}" >> ${GITHUB_OUTPUT}
      - name: Build, tag and publish docker image
        id: docker-publish
        uses: infrastructure-blocks/docker-publish-action@v1
        with:
          service: base
          tags: ${{ fromJson(inputs.tags) }}
          build-arguments: '{"ALPINE_VERSION": "${{ steps.infer-alpine-version.outputs.alpine-version }}"}'
      - name: Show published images
        run: |
          echo "${{ steps.docker-publish.outputs.published }}"
